// Comprehensive business types list — 400+ entries
export const BUSINESS_TYPES: string[] = [
    // Food & Beverage
    "Coffee Shop", "Café", "Espresso Bar", "Coffee Roastery", "Tea House", "Bubble Tea Shop",
    "Juice Bar", "Smoothie Bar", "Restaurant", "Fine Dining Restaurant", "Fast Food Restaurant",
    "Casual Dining Restaurant", "Family Restaurant", "Buffet Restaurant", "Food Truck",
    "Pop-Up Restaurant", "Ghost Kitchen", "Virtual Restaurant", "Diner", "Bistro",
    "Brasserie", "Gastropub", "Pub", "Bar", "Cocktail Bar", "Wine Bar", "Beer Bar",
    "Sports Bar", "Nightclub", "Lounge", "Rooftop Bar", "Speakeasy", "Brewery",
    "Microbrewery", "Craft Brewery", "Winery", "Vineyard", "Distillery", "Cider House",
    "Taproom", "Bakery", "Artisan Bakery", "Pastry Shop", "Cake Shop", "Cupcake Shop",
    "Donut Shop", "Bagel Shop", "Sandwich Shop", "Deli", "Delicatessen", "Butcher Shop",
    "Fish Market", "Fishmonger", "Farmers Market", "Grocery Store", "Supermarket",
    "Convenience Store", "Organic Food Store", "Health Food Store", "Specialty Food Store",
    "Gourmet Food Store", "International Food Store", "Ethnic Grocery", "Food Importer",
    "Food Distributor", "Food Manufacturer", "Food Processor", "Catering Company",
    "Wedding Caterer", "Corporate Caterer", "Meal Prep Service", "Meal Kit Delivery",
    "Food Delivery Service", "Pizza Shop", "Italian Restaurant", "Chinese Restaurant",
    "Japanese Restaurant", "Korean Restaurant", "Thai Restaurant", "Vietnamese Restaurant",
    "Indian Restaurant", "Mexican Restaurant", "Greek Restaurant", "Mediterranean Restaurant",
    "Middle Eastern Restaurant", "Lebanese Restaurant", "Turkish Restaurant",
    "African Restaurant", "Ethiopian Restaurant", "French Restaurant", "Spanish Restaurant",
    "American Restaurant", "BBQ Restaurant", "Steakhouse", "Seafood Restaurant",
    "Sushi Restaurant", "Ramen Shop", "Noodle Shop", "Taco Shop", "Burrito Shop",
    "Ice Cream Shop", "Gelato Shop", "Frozen Yogurt Shop", "Dessert Shop", "Candy Store",
    "Chocolate Shop", "Confectionery", "Snack Food Company",

    // Retail
    "Retail Store", "Boutique", "Clothing Store", "Fashion Boutique", "Menswear Store",
    "Womenswear Store", "Kids Clothing Store", "Baby Clothing Store", "Sportswear Store",
    "Athletic Wear Store", "Outdoor Clothing Store", "Uniform Supplier", "Workwear Store",
    "Shoe Store", "Sneaker Store", "Boot Store", "Handbag Store", "Accessories Store",
    "Jewelry Store", "Jewelry Designer", "Watch Store", "Eyewear Store", "Optician",
    "Sunglasses Store", "Cosmetics Store", "Beauty Supply Store", "Skincare Store",
    "Perfume Store", "Hair Care Store", "Nail Supply Store", "Home Goods Store",
    "Furniture Store", "Home Decor Store", "Kitchenware Store", "Bedding Store",
    "Lighting Store", "Appliance Store", "Electronics Store", "Computer Store",
    "Phone Store", "Gaming Store", "Toy Store", "Baby Store", "Book Store",
    "Used Book Store", "Comic Book Store", "Music Store", "Instrument Store",
    "Vinyl Record Store", "Hobby Store", "Craft Store", "Art Supply Store",
    "Fabric Store", "Sewing Supply Store", "Hardware Store", "Home Improvement Store",
    "Garden Center", "Plant Nursery", "Pet Store", "Pet Supply Store",
    "Sporting Goods Store", "Bike Shop", "Surf Shop", "Ski Shop", "Fishing Store",
    "Hunting Store", "Camping Store", "Outdoor Gear Store", "Pharmacy", "Drug Store",
    "Medical Supply Store", "Gift Shop", "Souvenir Shop", "Antique Store", "Thrift Store",
    "Consignment Store", "Pawn Shop", "Dollar Store", "Discount Store", "Liquidation Store",
    "Pop-Up Shop", "Market Stall", "Online Retailer", "E-commerce Store", "Wholesale Retailer",

    // Health & Wellness
    "Gym", "Fitness Center", "Health Club", "CrossFit Box", "Yoga Studio", "Pilates Studio",
    "Spin Studio", "Cycling Studio", "Barre Studio", "Dance Studio", "Martial Arts Studio",
    "Boxing Gym", "MMA Gym", "Rock Climbing Gym", "Swimming Pool", "Aquatic Center",
    "Personal Training Studio", "Boot Camp", "Wellness Center", "Holistic Health Center",
    "Spa", "Day Spa", "Medical Spa", "Medi-Spa", "Massage Therapy", "Massage Parlor",
    "Float Tank Center", "Infrared Sauna Studio", "Cryotherapy Center", "IV Therapy Clinic",
    "Nutritionist", "Dietitian Office", "Weight Loss Clinic", "Hypnosis Center",
    "Acupuncture Clinic", "Chiropractic Clinic", "Osteopath Office", "Physical Therapy Clinic",
    "Occupational Therapy Clinic", "Speech Therapy Clinic", "Mental Health Clinic",
    "Psychiatry Practice", "Psychology Practice", "Counseling Center", "Therapy Office",
    "Rehab Center", "Addiction Treatment Center", "Detox Center",

    // Medical & Healthcare
    "Doctor's Office", "General Practice", "Medical Clinic", "Family Medicine Practice",
    "Pediatric Clinic", "OB/GYN Practice", "Dermatology Clinic", "Cardiology Clinic",
    "Orthopedic Clinic", "Neurology Clinic", "Oncology Clinic", "Radiology Center",
    "Imaging Center", "Urgent Care Clinic", "Emergency Clinic", "Hospital",
    "Surgery Center", "Ambulatory Surgical Center", "Plastic Surgery Clinic",
    "Cosmetic Surgery Center", "Laser Eye Clinic", "LASIK Center", "Eye Care Center",
    "Optometry Practice", "Ophthalmology Practice", "Dental Office", "Dentist",
    "General Dentist", "Cosmetic Dentist", "Orthodontist", "Periodontist",
    "Oral Surgeon", "Endodontist", "Pedodontist", "Dental Specialist",
    "Veterinary Clinic", "Animal Hospital", "Pet Clinic", "Exotic Animal Clinic",

    // Beauty & Personal Care
    "Hair Salon", "Barber Shop", "Hair Stylist", "Hair Colorist", "Hair Extensions Studio",
    "Nail Salon", "Nail Bar", "Manicure Studio", "Pedicure Studio", "Nail Art Studio",
    "Waxing Studio", "Threading Studio", "Laser Hair Removal Clinic", "Electrolysis Studio",
    "Tattoo Parlor", "Tattoo Studio", "Piercing Studio", "Microblading Studio",
    "Eyelash Extension Studio", "Permanent Makeup Studio", "Skin Care Clinic",
    "Facialist", "Esthetician", "Makeup Artist", "Bridal Beauty Studio",
    "Mobile Beauty Services", "Tanning Salon", "Spray Tan Studio",

    // Professional Services
    "Law Firm", "Law Office", "Attorney", "Lawyer", "Solicitor", "Barrister",
    "Legal Consultant", "Patent Attorney", "Immigration Attorney", "Family Law Attorney",
    "Criminal Defense Attorney", "Personal Injury Attorney", "Corporate Law Firm",
    "Real Estate Attorney", "Estate Planning Attorney", "Bankruptcy Attorney",
    "Tax Attorney", "Environmental Law Firm", "Accounting Firm", "CPA Firm",
    "Bookkeeping Service", "Tax Preparation Service", "Tax Consultant", "Auditing Firm",
    "Financial Advisor", "Financial Planner", "Wealth Management Firm",
    "Investment Advisor", "Insurance Agency", "Insurance Broker", "Mortgage Broker",
    "Mortgage Lender", "Loan Company", "Credit Union", "Bank", "Private Bank",
    "Investment Bank", "Venture Capital Firm", "Private Equity Firm", "Hedge Fund",
    "Family Office", "Consulting Firm", "Management Consulting", "Strategy Consulting",
    "HR Consulting", "IT Consulting", "Business Consulting", "Operations Consulting",
    "Supply Chain Consulting", "Environmental Consulting", "Engineering Consulting",
    "Architecture Firm", "Interior Design Firm", "Graphic Design Agency",
    "Branding Agency", "Marketing Agency", "Digital Marketing Agency",
    "Social Media Agency", "Content Marketing Agency", "SEO Agency", "PPC Agency",
    "Email Marketing Agency", "Influencer Marketing Agency", "Advertising Agency",
    "Media Buying Agency", "PR Agency", "Public Relations Firm", "Communications Agency",
    "Event Planning Company", "Event Management Company", "Wedding Planning Company",
    "Corporate Event Planner", "Staffing Agency", "Recruiting Firm", "Headhunting Firm",
    "Executive Search Firm", "Temp Agency", "HR Services Company", "Payroll Service",
    "Security Company", "Private Investigation Firm", "Process Serving Company",
    "Translation Service", "Interpretation Service", "Notary",

    // Technology & Software
    "Software Company", "Software Development Company", "SaaS Company", "Tech Startup",
    "App Development Company", "Mobile App Developer", "Web Development Agency",
    "Web Design Agency", "UX/UI Design Agency", "Cybersecurity Company",
    "IT Support Company", "Managed Service Provider", "Cloud Services Company",
    "Data Analytics Company", "AI Company", "Machine Learning Company",
    "Blockchain Company", "Fintech Company", "Healthtech Company", "Edtech Company",
    "Proptech Company", "Legaltech Company", "Martech Company", "Adtech Company",
    "IoT Company", "Hardware Company", "Electronics Manufacturer", "Semiconductor Company",
    "Telecom Company", "Internet Service Provider", "VoIP Provider", "Data Center",
    "Hosting Company", "Domain Registrar", "E-commerce Platform", "CRM Company",
    "ERP Company", "Project Management Software Company", "HR Software Company",
    "Accounting Software Company", "POS Software Company", "Video Game Developer",
    "Game Studio", "AR/VR Company", "Drone Company", "Robotics Company",

    // Education
    "School", "Private School", "Charter School", "Boarding School", "International School",
    "Language School", "Tutoring Center", "Tutoring Service", "Test Prep Center",
    "College", "University", "Community College", "Trade School", "Vocational School",
    "Coding Bootcamp", "Music School", "Art School", "Dance School",
    "Driving School", "Flight School", "Culinary School", "Online Learning Platform",
    "Corporate Training Company", "Leadership Training", "Sales Training Company",
    "Coaching Business", "Life Coach", "Executive Coach", "Business Coach",
    "Career Coach", "Sports Coach", "Academic Tutoring",

    // Real Estate & Construction
    "Real Estate Agency", "Real Estate Brokerage", "Property Management Company",
    "Real Estate Developer", "Home Builder", "Custom Home Builder", "Commercial Real Estate",
    "Real Estate Investment Company", "Property Investment Firm", "Mortgage Company",
    "Home Inspection Service", "Real Estate Appraisal", "Land Surveying Company",
    "Construction Company", "General Contractor", "Subcontractor", "Renovation Company",
    "Remodeling Contractor", "Home Improvement Company", "Roofing Company",
    "Plumbing Company", "Electrical Contractor", "HVAC Company", "Flooring Company",
    "Painting Company", "Landscaping Company", "Lawn Care Service", "Tree Service",
    "Snow Removal Service", "Pool Company", "Pool Installation", "Deck Builder",
    "Fence Company", "Concrete Company", "Masonry Company", "Demolition Company",
    "Excavation Company", "Paving Company", "Waterproofing Company", "Insulation Company",
    "Window Company", "Door Company", "Garage Door Company", "Cabinet Maker",
    "Interior Decorator", "Stager", "Moving Company", "Storage Company",
    "Cleaning Service", "Janitorial Service", "Maid Service", "Commercial Cleaning",
    "Carpet Cleaning", "Pressure Washing", "Window Cleaning",

    // Automotive
    "Auto Dealership", "Used Car Dealership", "Car Rental Company", "Car Leasing Company",
    "Auto Repair Shop", "Auto Body Shop", "Oil Change Shop", "Tire Shop",
    "Auto Parts Store", "Car Wash", "Auto Detailing", "Towing Company",
    "Roadside Assistance", "Driving School", "Auto Auction", "Motorcycle Dealership",
    "Motorcycle Repair", "Boat Dealership", "RV Dealership", "Truck Dealership",

    // Transportation & Logistics
    "Trucking Company", "Freight Company", "Logistics Company", "Shipping Company",
    "Courier Service", "Last-Mile Delivery", "Warehousing Company",
    "Cold Storage Facility", "Fulfillment Center", "3PL Provider",
    "Customs Broker", "Import/Export Company", "Taxi Company", "Rideshare Company",
    "Limo Service", "Charter Bus Company", "Airport Shuttle", "Tour Operator",
    "Travel Agency", "Travel Management Company", "Airline", "Cargo Airline",

    // Media & Entertainment
    "Production Company", "Film Production Company", "TV Production Company",
    "Video Production Company", "Photography Studio", "Photographer",
    "Wedding Photographer", "Commercial Photographer", "Podcast Studio",
    "Recording Studio", "Music Production Company", "Record Label", "Talent Agency",
    "Modeling Agency", "Casting Agency", "Entertainment Agency", "Booking Agency",
    "Publishing Company", "Magazine", "Newspaper", "Blog", "Media Company",
    "Digital Media Company", "Streaming Service", "Podcast Network",
    "Animation Studio", "Post-Production Company", "VFX Studio",
    "Radio Station", "TV Station", "News Station",

    // Hospitality & Tourism
    "Hotel", "Boutique Hotel", "Bed and Breakfast", "Motel", "Hostel",
    "Vacation Rental", "Resort", "Luxury Resort", "Spa Resort", "Golf Resort",
    "Casino", "Casino Hotel", "Theme Park", "Amusement Park",
    "Museum", "Art Gallery", "Theater", "Concert Hall", "Event Venue",
    "Wedding Venue", "Conference Center", "Convention Center",
    "Tour Company", "Bike Tour Company", "Walking Tour Company", "Boat Tour Company",
    "Scuba Diving Center", "Surf School", "Ski Resort", "Golf Course", "Country Club",
    "Sports Club", "Tennis Club", "Yacht Club",

    // Non-Profit & Social Enterprise
    "Non-Profit Organization", "Charity", "Foundation", "NGO",
    "Social Enterprise", "Community Organization", "Religious Organization",
    "Church", "Mosque", "Synagogue", "Temple", "Faith-Based Organization",
    "Think Tank", "Research Institute", "Advocacy Group", "Trade Association",
    "Professional Association", "Chamber of Commerce",

    // Manufacturing & Industrial
    "Manufacturing Company", "Factory", "Plant", "Fabrication Shop",
    "Metal Fabricator", "Welding Company", "Printing Company", "Packaging Company",
    "Textile Company", "Clothing Manufacturer", "Shoe Manufacturer",
    "Furniture Manufacturer", "Wood Products Company", "Paper Products Company",
    "Plastic Manufacturer", "Chemical Company", "Pharmaceutical Company",
    "Medical Device Company", "Aerospace Company", "Defense Contractor",
    "Energy Company", "Oil & Gas Company", "Renewable Energy Company",
    "Solar Installation Company", "Wind Energy Company", "Mining Company",
    "Agriculture Company", "Farm", "Organic Farm", "Winery", "Brewery",
    "Food Processing Plant",

    // Financial Services
    "Payment Processing Company", "Merchant Services", "POS Solutions",
    "Invoice Factoring Company", "Equipment Leasing Company", "Payday Loan Company",
    "Debt Collection Agency", "Credit Repair Service", "Financial Planning Firm",
    "Retirement Planning", "Tax Resolution Company", "Crypto Exchange",
    "Digital Wallet Company", "Remittance Company", "Foreign Exchange Broker",

    // Government & Public Sector
    "Government Agency", "City Council", "Public School District",
    "Public Healthcare", "Military Contractor",

    // Miscellaneous
    "Laundry Service", "Dry Cleaning", "Alterations & Tailoring", "Cobbler", "Locksmith",
    "Appliance Repair", "Furniture Repair", "Electronics Repair", "Phone Repair Shop",
    "Seamstress", "Tailor", "Watch Repair", "Jewelry Repair", "Clock Repair",
    "Upholstery Shop", "Photo Shop", "Framing Shop", "Trophy Shop", "Engraving Service",
    "Sign Company", "Signage Company", "Banner Printing", "Embroidery Shop",
    "Screen Printing", "Promotional Products Company", "Vending Machine Company",
    "ATM Company", "Coin-Operated Laundry", "Self-Storage", "Auction House",
    "Pawn Shop", "Check Cashing", "Ticket Broker", "Game Arcade", "Escape Room",
    "Bowling Alley", "Mini Golf", "Go-Kart Track", "Laser Tag Arena",
    "Trampoline Park", "Water Park", "Skate Park", "Shooting Range", "Archery Range",
    "Fishing Charter", "Hunting Guide", "Dog Grooming", "Dog Training",
    "Pet Boarding", "Pet Daycare", "Pet Photography", "Animal Rescue",
    "Veterinary Specialist", "Animal Shelter", "Pet Transportation",
];

export default BUSINESS_TYPES;
